/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'
const file = 'assets/grid/beijing/Beijing1.gltf';
export default function Beijing1({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(file)
  return (
    <group ref={group} {...props} dispose={null}  onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cylinder045.geometry} material={materials.floorpentagon} position={[1.09, -3, 3.73]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials.floorpentagon} position={[-30.04, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials.floorpentagon} position={[-14.45, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials.floorpentagon} position={[1.13, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials.floorpentagon} position={[16.71, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials.floorpentagon} position={[32.29, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials.floorpentagon} position={[37.05, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials.floorpentagon} position={[41.85, 3.84, 16.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials.floorpentagon} position={[46.8, 3.84, 2.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials.floorpentagon} position={[51.46, 3.84, -12.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials.floorpentagon} position={[38.84, 3.84, -21.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials.floorpentagon} position={[26.21, 3.84, -31.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials.floorpentagon} position={[13.58, 3.84, -40.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials.floorpentagon} position={[1.1, 3.84, -49.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials.floorpentagon} position={[-11.39, 3.84, -40.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials.floorpentagon} position={[-23.92, 3.84, -31.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder061.geometry} material={materials.floorpentagon} position={[-36.55, 3.84, -21.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder062.geometry} material={materials.floorpentagon} position={[-49.18, 3.84, -12.71]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder063.geometry} material={materials.floorpentagon} position={[-44.49, 3.84, 2.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder064.geometry} material={materials.floorpentagon} position={[-39.67, 3.84, 16.93]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder065.geometry} material={materials.floorpentagon} position={[-34.82, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder066.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder067.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder068.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder069.geometry} material={materials.floorpentagon} position={[-7.97, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder070.geometry} material={materials.floorpentagon} position={[1.18, 3.84, 4.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder071.geometry} material={materials.floorpentagon} position={[1.18, 3.84, 19.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder072.geometry} material={materials.floorpentagon} position={[10.33, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder073.geometry} material={materials.floorpentagon} position={[24.42, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder074.geometry} material={materials.floorpentagon} position={[24.42, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder075.geometry} material={materials.floorpentagon} position={[24.42, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder196.geometry} material={materials['grad.001']} position={[-35.06, 12.63, 32.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder197.geometry} material={materials['grad.001']} position={[16.55, 12.63, 46.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder198.geometry} material={materials['grad.001']} position={[32.36, 12.63, 46.62]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder199.geometry} material={materials['grad.001']} position={[1.34, 12.63, -49.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder200.geometry} material={materials['grad.001']} position={[-24.13, 12.63, -31.45]} rotation={[Math.PI / 2, 0, -0.09]} scale={0.01} />
      <mesh geometry={nodes.Cylinder201.geometry} material={materials['grad.001']} position={[-36.77, 12.63, -22.47]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01} />
      <mesh geometry={nodes.Cylinder202.geometry} material={materials['grad.001']} position={[-30.19, 12.63, 46.83]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.01} />
      <mesh geometry={nodes.Cylinder203.geometry} material={materials['grad.001']} position={[-39.77, 12.63, 16.55]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder204.geometry} material={materials['grad.001']} position={[24.96, 12.63, 16.94]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder205.geometry} material={materials['grad.001']} position={[-44.77, 12.63, 1.83]} rotation={[Math.PI / 2, 0, -2.26]} scale={0.01} />
      <mesh geometry={nodes.Cylinder206.geometry} material={materials['grad.001']} position={[-13.91, 12.63, 46.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder207.geometry} material={materials['grad.001']} position={[-21.97, 12.63, 2.5]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder208.geometry} material={materials['grad.001']} position={[51.46, 12.63, -13.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder209.geometry} material={materials['grad.001']} position={[-21.99, 12.63, 16.75]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder210.geometry} material={materials['grad.001']} position={[-11.55, 12.63, -40.84]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder211.geometry} material={materials['grad.001']} position={[-49.41, 12.63, -12.57]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder212.geometry} material={materials['grad.001']} position={[24.91, 12.63, -13.11]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder213.geometry} material={materials['grad.001']} position={[26.35, 12.63, -31.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder214.geometry} material={materials['grad.001']} position={[42.91, 12.63, 16.95]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder215.geometry} material={materials['grad.001']} position={[-7.43, 12.63, -7.71]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder216.geometry} material={materials['grad.001']} position={[24.45, 12.63, 2.17]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder217.geometry} material={materials['grad.001']} position={[11.33, 12.63, -7.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder218.geometry} material={materials['grad.001']} position={[-22.42, 12.63, -12.39]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder219.geometry} material={materials['grad.001']} position={[1.52, 12.63, 46.82]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder220.geometry} material={materials['grad.001']} position={[13.65, 12.63, -40.66]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder221.geometry} material={materials['grad.001']} position={[39.36, 12.63, -22.47]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder222.geometry} material={materials['grad.001']} position={[47.82, 12.63, 1.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder223.geometry} material={materials['grad.001']} position={[37.04, 12.63, 32.22]} rotation={[Math.PI / 2, 0, 0.16]} scale={0.01} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.windows} position={[1.64, 4.65, 4.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.03} />
      <mesh geometry={nodes.HZ_building_116_1.geometry} material={materials.grad} position={[1.42, 4.64, 19.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(file)
