/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'
const file = 'assets/grid/beijing/Beijing2.gltf';

export default function Beijing2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(file)
  return (
    <group ref={group} {...props} dispose={null}  onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.floorpentagon} position={[1.09, -3, 3.73]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder108.geometry} material={materials.floorpentagon} position={[-30, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder109.geometry} material={materials.floorpentagon} position={[-14.42, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder110.geometry} material={materials.floorpentagon} position={[1.16, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder111.geometry} material={materials.floorpentagon} position={[16.75, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder112.geometry} material={materials.floorpentagon} position={[32.33, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder113.geometry} material={materials.floorpentagon} position={[37.09, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder114.geometry} material={materials.floorpentagon} position={[41.89, 3.84, 16.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder115.geometry} material={materials.floorpentagon} position={[46.84, 3.84, 2.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder116.geometry} material={materials.floorpentagon} position={[51.5, 3.84, -12.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder117.geometry} material={materials.floorpentagon} position={[38.87, 3.84, -21.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder118.geometry} material={materials.floorpentagon} position={[26.25, 3.84, -31.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder119.geometry} material={materials.floorpentagon} position={[13.62, 3.84, -40.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder120.geometry} material={materials.floorpentagon} position={[1.14, 3.84, -49.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder121.geometry} material={materials.floorpentagon} position={[-11.35, 3.84, -40.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder122.geometry} material={materials.floorpentagon} position={[-23.88, 3.84, -31.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder123.geometry} material={materials.floorpentagon} position={[-36.51, 3.84, -21.87]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder124.geometry} material={materials.floorpentagon} position={[-49.14, 3.84, -12.71]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder125.geometry} material={materials.floorpentagon} position={[-44.45, 3.84, 2.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder126.geometry} material={materials.floorpentagon} position={[-39.63, 3.84, 16.93]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder127.geometry} material={materials.floorpentagon} position={[-34.79, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder128.geometry} material={materials.floorpentagon} position={[-22.18, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder129.geometry} material={materials.floorpentagon} position={[-22.18, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder130.geometry} material={materials.floorpentagon} position={[-22.18, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder131.geometry} material={materials.floorpentagon} position={[-7.93, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder132.geometry} material={materials.floorpentagon} position={[1.21, 3.84, 4.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder133.geometry} material={materials.floorpentagon} position={[1.21, 3.84, 19.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder134.geometry} material={materials.floorpentagon} position={[10.36, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder135.geometry} material={materials.floorpentagon} position={[24.46, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder136.geometry} material={materials.floorpentagon} position={[24.46, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder137.geometry} material={materials.floorpentagon} position={[24.46, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder252.geometry} material={materials['grad.001']} position={[-35.02, 14.36, 32.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder253.geometry} material={materials['grad.001']} position={[16.58, 14.36, 46.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder254.geometry} material={materials['grad.001']} position={[32.4, 14.36, 46.62]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder255.geometry} material={materials['grad.001']} position={[1.37, 14.36, -49.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder256.geometry} material={materials['grad.001']} position={[-24.09, 14.36, -31.45]} rotation={[Math.PI / 2, 0, -0.09]} scale={0.01} />
      <mesh geometry={nodes.Cylinder257.geometry} material={materials['grad.001']} position={[-36.73, 14.36, -22.47]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01} />
      <mesh geometry={nodes.Cylinder258.geometry} material={materials['grad.001']} position={[-30.16, 14.36, 46.83]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.01} />
      <mesh geometry={nodes.Cylinder259.geometry} material={materials['grad.001']} position={[-39.73, 14.36, 16.55]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder260.geometry} material={materials['grad.001']} position={[25, 14.36, 16.94]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder261.geometry} material={materials['grad.001']} position={[-44.73, 14.36, 1.83]} rotation={[Math.PI / 2, 0, -2.26]} scale={0.01} />
      <mesh geometry={nodes.Cylinder262.geometry} material={materials['grad.001']} position={[-13.87, 14.36, 46.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder263.geometry} material={materials['grad.001']} position={[-21.93, 14.36, 2.5]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder264.geometry} material={materials['grad.001']} position={[51.5, 14.36, -13.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder265.geometry} material={materials['grad.001']} position={[-21.95, 14.36, 16.75]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder266.geometry} material={materials['grad.001']} position={[-11.51, 14.36, -40.84]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder267.geometry} material={materials['grad.001']} position={[-49.38, 14.36, -12.57]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder268.geometry} material={materials['grad.001']} position={[24.95, 14.36, -13.11]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder269.geometry} material={materials['grad.001']} position={[26.39, 14.36, -31.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder270.geometry} material={materials['grad.001']} position={[42.95, 14.36, 16.95]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder271.geometry} material={materials['grad.001']} position={[-7.39, 14.36, -7.71]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder272.geometry} material={materials['grad.001']} position={[24.48, 14.36, 2.17]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder273.geometry} material={materials['grad.001']} position={[11.37, 14.36, -7.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder274.geometry} material={materials['grad.001']} position={[-22.38, 14.36, -12.39]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder275.geometry} material={materials['grad.001']} position={[1.55, 14.36, 46.82]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder276.geometry} material={materials['grad.001']} position={[13.68, 14.36, -40.66]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder277.geometry} material={materials['grad.001']} position={[39.4, 14.36, -22.47]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder278.geometry} material={materials['grad.001']} position={[47.86, 14.36, 1.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder279.geometry} material={materials['grad.001']} position={[37.08, 14.36, 32.22]} rotation={[Math.PI / 2, 0, 0.16]} scale={0.01} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.grad} position={[1.1, 8.08, 5.25]} rotation={[Math.PI / 2, 0, -2.08]} scale={0.01} />
      <mesh geometry={nodes.skpF375_001.geometry} material={materials.grad} position={[1.35, 4.99, 20.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(file)
