/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'
const file = 'assets/grid/beijing/Beijing5.gltf';


export default function Beijing5({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(file)
  return (
    <group ref={group} {...props} dispose={null}  onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cube005.geometry} material={materials.grad} position={[1.73, 7.18, 5.22]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.grad} position={[0.8, 7.64, 20.97]} rotation={[Math.PI / 2, 0, 0.42]} scale={0.01} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.floorpentagon} position={[1.88, -3, 3.73]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder077.geometry} material={materials.floorpentagon} position={[-29.22, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder078.geometry} material={materials.floorpentagon} position={[-13.64, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials.floorpentagon} position={[1.94, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials.floorpentagon} position={[17.52, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder081.geometry} material={materials.floorpentagon} position={[33.1, 3.84, 46.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder082.geometry} material={materials.floorpentagon} position={[37.86, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder083.geometry} material={materials.floorpentagon} position={[42.66, 3.84, 16.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder084.geometry} material={materials.floorpentagon} position={[47.61, 3.84, 2.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder085.geometry} material={materials.floorpentagon} position={[52.27, 3.84, -12.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder086.geometry} material={materials.floorpentagon} position={[39.65, 3.84, -21.85]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder087.geometry} material={materials.floorpentagon} position={[27.02, 3.84, -31.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder088.geometry} material={materials.floorpentagon} position={[14.4, 3.84, -40.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder089.geometry} material={materials.floorpentagon} position={[1.91, 3.84, -49.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder090.geometry} material={materials.floorpentagon} position={[-10.58, 3.84, -40.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder091.geometry} material={materials.floorpentagon} position={[-23.11, 3.84, -31.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder092.geometry} material={materials.floorpentagon} position={[-35.74, 3.84, -21.87]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder093.geometry} material={materials.floorpentagon} position={[-48.37, 3.84, -12.71]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder094.geometry} material={materials.floorpentagon} position={[-43.68, 3.84, 2.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder095.geometry} material={materials.floorpentagon} position={[-38.85, 3.84, 16.93]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder096.geometry} material={materials.floorpentagon} position={[-34.01, 3.84, 31.77]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder097.geometry} material={materials.floorpentagon} position={[-21.41, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder098.geometry} material={materials.floorpentagon} position={[-21.41, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder099.geometry} material={materials.floorpentagon} position={[-21.41, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder100.geometry} material={materials.floorpentagon} position={[-7.16, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder101.geometry} material={materials.floorpentagon} position={[1.99, 3.84, 4.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder102.geometry} material={materials.floorpentagon} position={[1.99, 3.84, 19.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder103.geometry} material={materials.floorpentagon} position={[11.14, 3.84, -7.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder104.geometry} material={materials.floorpentagon} position={[25.23, 3.84, -12.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder105.geometry} material={materials.floorpentagon} position={[25.23, 3.84, 2.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder106.geometry} material={materials.floorpentagon} position={[25.23, 3.84, 17.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder224.geometry} material={materials['grad.001']} position={[-34.24, 14.36, 32.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder225.geometry} material={materials['grad.001']} position={[17.36, 14.36, 46.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder226.geometry} material={materials['grad.001']} position={[33.18, 14.36, 46.62]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder227.geometry} material={materials['grad.001']} position={[2.15, 14.36, -49.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder228.geometry} material={materials['grad.001']} position={[-23.31, 14.36, -31.45]} rotation={[Math.PI / 2, 0, -0.09]} scale={0.01} />
      <mesh geometry={nodes.Cylinder229.geometry} material={materials['grad.001']} position={[-35.96, 14.36, -22.47]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01} />
      <mesh geometry={nodes.Cylinder230.geometry} material={materials['grad.001']} position={[-29.38, 14.36, 46.83]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.01} />
      <mesh geometry={nodes.Cylinder231.geometry} material={materials['grad.001']} position={[-38.96, 14.36, 16.55]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder232.geometry} material={materials['grad.001']} position={[25.78, 14.36, 16.94]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder233.geometry} material={materials['grad.001']} position={[-43.96, 14.36, 1.83]} rotation={[Math.PI / 2, 0, -2.26]} scale={0.01} />
      <mesh geometry={nodes.Cylinder234.geometry} material={materials['grad.001']} position={[-13.1, 14.36, 46.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder235.geometry} material={materials['grad.001']} position={[-21.16, 14.36, 2.5]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder236.geometry} material={materials['grad.001']} position={[52.27, 14.36, -13.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder237.geometry} material={materials['grad.001']} position={[-21.18, 14.36, 16.75]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder238.geometry} material={materials['grad.001']} position={[-10.74, 14.36, -40.84]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder239.geometry} material={materials['grad.001']} position={[-48.6, 14.36, -12.57]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder240.geometry} material={materials['grad.001']} position={[25.72, 14.36, -13.11]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder241.geometry} material={materials['grad.001']} position={[27.16, 14.36, -31.46]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder242.geometry} material={materials['grad.001']} position={[43.72, 14.36, 16.95]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder243.geometry} material={materials['grad.001']} position={[-6.62, 14.36, -7.71]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder244.geometry} material={materials['grad.001']} position={[25.26, 14.36, 2.17]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder245.geometry} material={materials['grad.001']} position={[12.14, 14.36, -7.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder246.geometry} material={materials['grad.001']} position={[-21.61, 14.36, -12.39]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder247.geometry} material={materials['grad.001']} position={[2.33, 14.36, 46.82]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder248.geometry} material={materials['grad.001']} position={[14.46, 14.36, -40.66]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder249.geometry} material={materials['grad.001']} position={[40.17, 14.36, -22.47]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder250.geometry} material={materials['grad.001']} position={[48.63, 14.36, 1.46]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder251.geometry} material={materials['grad.001']} position={[37.85, 14.36, 32.22]} rotation={[Math.PI / 2, 0, 0.16]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(file)
