/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import file from 'assets/penta.gltf';
import { Vector3 } from 'three'
export default function Item({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('assets/penta.gltf');

  return (
    <group ref={group} {...props} dispose={null} onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cube_Cube_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cube_Cube_emission1.geometry} material={materials.emission1} />
      <mesh geometry={nodes.Circle001_Circle001_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.Circle001_Circle001_emission4.geometry} material={materials.emission4} />
      <mesh geometry={nodes.Cube003_Cube018_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cube003_Cube018_emission1.geometry} material={materials.emission1} />
      <mesh geometry={nodes.building_50_Cube036_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_50_Cube036_emission4.geometry} material={materials.emission4} />
      <mesh geometry={nodes.building_53_Untitled022_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_53_Untitled022_emission3.geometry} material={materials.emission3} />
      <mesh geometry={nodes.building_66_Cylinder012_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_66_Cylinder012_emission1.geometry} material={materials.emission1} />
      <mesh geometry={nodes.building_73_Cube050_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_73_Cube050_emission2.geometry} material={materials.emission2} />
      <mesh geometry={nodes.building_37001_Cube016_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_37001_Cube016_emission2.geometry} material={materials.emission2} />
      <mesh geometry={nodes.Downtown_Center_City014_Downtown_Center_City006_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.Downtown_Center_City014_Downtown_Center_City006_Material117.geometry} material={materials['Material.117']} />
      <mesh geometry={nodes.Downtown_Center_City001_Downtown_Center_City001_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.Downtown_Center_City001_Downtown_Center_City001_emission4.geometry} material={materials.emission4} />
      <mesh geometry={nodes.city_buildingswindows003_city_buildingswindows003_grad.geometry} material={materials.grad} />
      <mesh geometry={nodes.city_buildingswindows003_city_buildingswindows003_emission2.geometry} material={materials.emission2} />
      <mesh geometry={nodes.Cube004_Cube020.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.floorpentagon} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder011_Cylinder009.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder012_Cylinder013.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder013_Cylinder014.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder014_Cylinder015.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder015_Cylinder017.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder016_Cylinder018.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder017_Cylinder019.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder018_Cylinder020.geometry} material={materials.grad} />
      <mesh geometry={nodes.Cylinder019_Cylinder021.geometry} material={materials.grad} />
      <mesh geometry={nodes.Circle003_Circle005.geometry} material={materials.grad} />
      <mesh geometry={nodes.Circle002_Circle006.geometry} material={materials.grad} />
      <mesh geometry={nodes.Circle004_Circle007.geometry} material={materials.grad} />
      <mesh geometry={nodes.building_37002_Cube017.geometry} material={materials.grad} />
      <mesh geometry={nodes.city_buildingswindows923.geometry} material={materials.grad} />
      <mesh geometry={nodes.city_buildingswindows002_city_buildingswindows001.geometry} material={materials.grad} />
    </group>
  )
}

useGLTF.preload('assets/penta.gltf')
