/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'
const file = 'assets/grid/osaka/osaka_p4.gltf';
export default function Osaka_p4({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(file)
  return (
    <group ref={group} {...props} dispose={null}  onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cylinder175.geometry} material={materials['grad.001']} position={[-34.89, 14.36, 28.42]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder174.geometry} material={materials['grad.001']} position={[16.71, 14.36, 43.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder173.geometry} material={materials['grad.001']} position={[32.53, 14.36, 42.79]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder172.geometry} material={materials['grad.001']} position={[1.5, 14.36, -53.29]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder171.geometry} material={materials['grad.001']} position={[-23.96, 14.36, -35.28]} rotation={[Math.PI / 2, 0, -0.09]} scale={0.01} />
      <mesh geometry={nodes.Cylinder170.geometry} material={materials['grad.001']} position={[-36.61, 14.36, -26.3]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01} />
      <mesh geometry={nodes.Cylinder169.geometry} material={materials['grad.001']} position={[-30.03, 14.36, 43]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.01} />
      <mesh geometry={nodes.Cylinder138.geometry} material={materials['grad.001']} position={[-39.61, 14.36, 12.72]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder107.geometry} material={materials['grad.001']} position={[25.13, 14.36, 13.11]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder076.geometry} material={materials['grad.001']} position={[-44.6, 14.36, -2.01]} rotation={[Math.PI / 2, 0, -2.26]} scale={0.01} />
      <mesh geometry={nodes.Cylinder176.geometry} material={materials['grad.001']} position={[-13.75, 14.36, 42.62]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder177.geometry} material={materials['grad.001']} position={[-21.8, 14.36, -1.33]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder178.geometry} material={materials['grad.001']} position={[51.62, 14.36, -16.99]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder179.geometry} material={materials['grad.001']} position={[-21.82, 14.36, 12.92]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder180.geometry} material={materials['grad.001']} position={[-11.39, 14.36, -44.67]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder181.geometry} material={materials['grad.001']} position={[-49.25, 14.36, -16.4]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder182.geometry} material={materials['grad.001']} position={[25.08, 14.36, -16.94]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder183.geometry} material={materials['grad.001']} position={[26.52, 14.36, -35.29]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder184.geometry} material={materials['grad.001']} position={[43.07, 14.36, 13.12]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder185.geometry} material={materials['grad.001']} position={[-7.27, 14.36, -11.55]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder186.geometry} material={materials['grad.001']} position={[24.61, 14.36, -1.66]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder187.geometry} material={materials['grad.001']} position={[11.49, 14.36, -11.23]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder188.geometry} material={materials['grad.001']} position={[-22.26, 14.36, -16.22]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder189.geometry} material={materials['grad.001']} position={[1.68, 14.36, 42.99]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder190.geometry} material={materials['grad.001']} position={[13.81, 14.36, -44.49]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder191.geometry} material={materials['grad.001']} position={[39.52, 14.36, -26.3]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder192.geometry} material={materials['grad.001']} position={[47.98, 14.36, -2.37]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder193.geometry} material={materials['grad.001']} position={[37.21, 14.36, 28.39]} rotation={[Math.PI / 2, 0, 0.16]} scale={0.01} />
      <mesh geometry={nodes.Pagoda005.geometry} material={materials['grad.002']} position={[0.54, 13.44, 0.61]} rotation={[-Math.PI, -0.57, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.grad} position={[0.61, 9.9, 16.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.floorpentagon} position={[1.09, -3, -0.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.floorpentagon} position={[-30.04, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.floorpentagon} position={[-14.45, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.floorpentagon} position={[1.13, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.floorpentagon} position={[16.71, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.floorpentagon} position={[32.29, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder020.geometry} material={materials.floorpentagon} position={[37.05, 3.84, 27.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials.floorpentagon} position={[41.85, 3.84, 13.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials.floorpentagon} position={[46.8, 3.84, -1.7]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials.floorpentagon} position={[51.46, 3.84, -16.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials.floorpentagon} position={[38.84, 3.84, -25.68]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials.floorpentagon} position={[26.21, 3.84, -34.84]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials.floorpentagon} position={[13.58, 3.84, -44]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials.floorpentagon} position={[1.1, 3.84, -53.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials.floorpentagon} position={[-11.39, 3.84, -44.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials.floorpentagon} position={[-23.92, 3.84, -34.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials.floorpentagon} position={[-36.55, 3.84, -25.7]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials.floorpentagon} position={[-49.18, 3.84, -16.54]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials.floorpentagon} position={[-44.49, 3.84, -1.72]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials.floorpentagon} position={[-39.67, 3.84, 13.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials.floorpentagon} position={[-34.82, 3.84, 27.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, -16.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, -1.45]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials.floorpentagon} position={[-22.22, 3.84, 13.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials.floorpentagon} position={[-7.97, 3.84, -11.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials.floorpentagon} position={[1.18, 3.84, 0.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials.floorpentagon} position={[1.18, 3.84, 15.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials.floorpentagon} position={[10.33, 3.84, -11.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials.floorpentagon} position={[24.42, 3.84, -16.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials.floorpentagon} position={[24.42, 3.84, -1.45]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials.floorpentagon} position={[24.42, 3.84, 13.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(file)
