/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'
const file = 'assets/grid/osaka/osaka_p2.gltf';

export default function Osaka_p2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(file)
  return (
    <group ref={group} {...props} dispose={null}  onPointerOver={props.onPointerOver} onPointerOut={props.onPointerOut} scale={new Vector3(0.022, 0.022, 0.022)} rotateX={[50]}>
      <mesh geometry={nodes.Cylinder280.geometry} material={materials['grad.001']} position={[-36.16, 14.36, 28.42]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder281.geometry} material={materials['grad.001']} position={[15.44, 14.36, 43.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder282.geometry} material={materials['grad.001']} position={[31.25, 14.36, 42.79]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder283.geometry} material={materials['grad.001']} position={[0.23, 14.36, -53.29]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder284.geometry} material={materials['grad.001']} position={[-25.23, 14.36, -35.28]} rotation={[Math.PI / 2, 0, -0.09]} scale={0.01} />
      <mesh geometry={nodes.Cylinder285.geometry} material={materials['grad.001']} position={[-37.88, 14.36, -26.3]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01} />
      <mesh geometry={nodes.Cylinder286.geometry} material={materials['grad.001']} position={[-31.3, 14.36, 43]} rotation={[Math.PI / 2, 0, 0.13]} scale={0.01} />
      <mesh geometry={nodes.Cylinder287.geometry} material={materials['grad.001']} position={[-40.88, 14.36, 12.72]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder288.geometry} material={materials['grad.001']} position={[23.85, 14.36, 13.11]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder289.geometry} material={materials['grad.001']} position={[-45.88, 14.36, -2.01]} rotation={[Math.PI / 2, 0, -2.26]} scale={0.01} />
      <mesh geometry={nodes.Cylinder290.geometry} material={materials['grad.001']} position={[-15.02, 14.36, 42.62]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder291.geometry} material={materials['grad.001']} position={[-23.08, 14.36, -1.33]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder292.geometry} material={materials['grad.001']} position={[50.35, 14.36, -16.99]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder293.geometry} material={materials['grad.001']} position={[-23.1, 14.36, 12.92]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder294.geometry} material={materials['grad.001']} position={[-12.66, 14.36, -44.67]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder295.geometry} material={materials['grad.001']} position={[-50.52, 14.36, -16.4]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder296.geometry} material={materials['grad.001']} position={[23.8, 14.36, -16.94]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder297.geometry} material={materials['grad.001']} position={[25.24, 14.36, -35.29]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder298.geometry} material={materials['grad.001']} position={[41.8, 14.36, 13.12]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder299.geometry} material={materials['grad.001']} position={[-8.54, 14.36, -11.55]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder300.geometry} material={materials['grad.001']} position={[23.34, 14.36, -1.66]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder301.geometry} material={materials['grad.001']} position={[10.22, 14.36, -11.23]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder302.geometry} material={materials['grad.001']} position={[-23.53, 14.36, -16.22]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder303.geometry} material={materials['grad.001']} position={[0.41, 14.36, 42.99]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder304.geometry} material={materials['grad.001']} position={[12.54, 14.36, -44.49]} rotation={[Math.PI / 2, 0, -0.53]} scale={0.01} />
      <mesh geometry={nodes.Cylinder305.geometry} material={materials['grad.001']} position={[38.25, 14.36, -26.3]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder306.geometry} material={materials['grad.001']} position={[46.71, 14.36, -2.37]} rotation={[Math.PI / 2, 0, -0.72]} scale={0.01} />
      <mesh geometry={nodes.Cylinder307.geometry} material={materials['grad.001']} position={[35.93, 14.36, 28.39]} rotation={[Math.PI / 2, 0, 0.16]} scale={0.01} />
      <mesh geometry={nodes.polySurface1302001.geometry} material={materials.grad} position={[-0.03, 9.94, 1.04]} rotation={[-Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.grad} position={[0.26, 4.59, 15.64]} rotation={[Math.PI / 2, 0, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.floorpentagon} position={[-0.07, -3, -0.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder139.geometry} material={materials.floorpentagon} position={[-31.15, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder140.geometry} material={materials.floorpentagon} position={[-15.56, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder141.geometry} material={materials.floorpentagon} position={[0.02, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder142.geometry} material={materials.floorpentagon} position={[15.6, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder143.geometry} material={materials.floorpentagon} position={[31.18, 3.84, 42.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder144.geometry} material={materials.floorpentagon} position={[35.94, 3.84, 27.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder145.geometry} material={materials.floorpentagon} position={[40.74, 3.84, 13.12]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder146.geometry} material={materials.floorpentagon} position={[45.69, 3.84, -1.7]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder147.geometry} material={materials.floorpentagon} position={[50.35, 3.84, -16.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder148.geometry} material={materials.floorpentagon} position={[37.73, 3.84, -25.68]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder149.geometry} material={materials.floorpentagon} position={[25.1, 3.84, -34.84]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder150.geometry} material={materials.floorpentagon} position={[12.47, 3.84, -44]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder151.geometry} material={materials.floorpentagon} position={[-0.01, 3.84, -53.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder152.geometry} material={materials.floorpentagon} position={[-12.5, 3.84, -44.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder153.geometry} material={materials.floorpentagon} position={[-25.03, 3.84, -34.86]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder154.geometry} material={materials.floorpentagon} position={[-37.66, 3.84, -25.7]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder155.geometry} material={materials.floorpentagon} position={[-50.29, 3.84, -16.54]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder156.geometry} material={materials.floorpentagon} position={[-45.6, 3.84, -1.72]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder157.geometry} material={materials.floorpentagon} position={[-40.78, 3.84, 13.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder158.geometry} material={materials.floorpentagon} position={[-35.93, 3.84, 27.94]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder159.geometry} material={materials.floorpentagon} position={[-23.33, 3.84, -16.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder160.geometry} material={materials.floorpentagon} position={[-23.33, 3.84, -1.45]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder161.geometry} material={materials.floorpentagon} position={[-23.33, 3.84, 13.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder162.geometry} material={materials.floorpentagon} position={[-9.08, 3.84, -11.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder163.geometry} material={materials.floorpentagon} position={[0.07, 3.84, 0.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder164.geometry} material={materials.floorpentagon} position={[0.07, 3.84, 15.65]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder165.geometry} material={materials.floorpentagon} position={[9.22, 3.84, -11.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder166.geometry} material={materials.floorpentagon} position={[23.31, 3.84, -16.15]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder167.geometry} material={materials.floorpentagon} position={[23.31, 3.84, -1.45]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cylinder168.geometry} material={materials.floorpentagon} position={[23.31, 3.84, 13.25]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(file)
